name: Firewall Rule Automation

on:
  push:
    branches:
      - noc
      - ip

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ github.ref_name }}
          title: "Update firewall rules for ${GITHUB_REF}"
          body: |
            This PR contains the following changes:
            - Added/Modified/Deleted firewall rules.
            - Please review the changes before merging.

  validate-and-apply:
    runs-on: ubuntu-latest
    needs: create-pr
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Validate Rules
        run: |
          cd teams/${{ github.ref_name }}
          python3 validate_rules.py

      - name: Detect Changes
        run: |
          cd teams/${{ github.ref_name }}
          python3 detect_changes.py

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init and Apply
        run: |
          cd teams/${{ github.ref_name }}
          terraform init
          terraform apply -auto-approve
        env:
          PALO_ALTO_HOSTNAME: ${{ secrets.PALO_ALTO_HOSTNAME }}
          PALO_ALTO_USERNAME: ${{ secrets.PALO_ALTO_USERNAME }}
          PALO_ALTO_PASSWORD: ${{ secrets.PALO_ALTO_PASSWORD }}

